"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, KeyRound, UserRound } from "lucide-react";
import { api } from "@/lib/api";
import { useSession } from "@/components/session-provider";
import { Button, Card, CardContent, CardHeader, CardTitle, Input } from "@/components/ui";

export default function SettingsPage() { const { user, logout } = useSession(); const [oldPassword, setOldPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const submit = async (event: FormEvent) => { event.preventDefault(); try { await api.post("/auth/password", { old_password: oldPassword, new_password: newPassword }); setMessage("密码修改成功，请重新登录。"); setTimeout(logout, 800); } catch { setMessage("密码修改失败，请检查原密码。"); } }; return <div className="max-w-2xl space-y-6"><Link className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground" href="/"><ArrowLeft className="h-4 w-4" />返回工作台</Link><div><p className="text-sm font-medium text-primary">账户</p><h1 className="mt-2 text-3xl font-bold">个人设置</h1></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-5 w-5 text-primary" />个人信息</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">姓名</p><p className="mt-1 font-medium">{user?.username}</p></div><div><p className="text-muted-foreground">年级</p><p className="mt-1 font-medium">{user?.grade || "未设置"}</p></div><div><p className="text-muted-foreground">班级</p><p className="mt-1 font-medium">{user?.classnum || "未设置"}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-primary" />修改密码</CardTitle></CardHeader><CardContent><form className="max-w-md space-y-4" onSubmit={submit}><Input type="password" placeholder="原密码" value={oldPassword} onChange={(e) => setOldPassword(e.target.value)} required /><Input type="password" placeholder="新密码（至少 8 位）" value={newPassword} onChange={(e) => setNewPassword(e.target.value)} required minLength={8} /><Button type="submit">确认修改</Button>{message && <p className="text-sm text-muted-foreground">{message}</p>}</form></CardContent></Card></div>; }
