"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, FilePlus2 } from "lucide-react";

import { api } from "@/lib/api";
import { Button, Card, CardContent, CardDescription, CardHeader, CardTitle, Input, Spinner } from "@/components/ui";
import type { UserChoice } from "@/lib/types";

export default function NewIssuePage() {
  const router = useRouter();
  const [form, setForm] = useState({ id: "", deadline: "", subject2: "", subject3: "", subject4: "", leaderId: "", editorIds: [] as string[], responsibleEditorId: "" });
  const [users, setUsers] = useState<UserChoice[]>([]);
  const [error, setError] = useState("");
  const [submitting, setSubmitting] = useState(false);
  useEffect(() => { api.get("/users/choices").then(({ data }) => setUsers(data)).catch(() => setError("用户列表加载失败，请刷新后重试。")); }, []);
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setSubmitting(true); try { await api.post("/issues", { id: Number(form.id), deadline: new Date(form.deadline).toISOString(), subject: [form.subject2, form.subject3, form.subject4], leader_id: form.leaderId ? Number(form.leaderId) : null, editor_ids: form.editorIds.map(Number), responsible_editor_id: form.responsibleEditorId ? Number(form.responsibleEditorId) : null }); router.push("/"); } catch { setError("创建失败，请确认期数未重复、人员选择有效且当前账号拥有创建权限。"); } finally { setSubmitting(false); } };
  const toggleEditor = (value: string) => setForm((current) => ({ ...current, editorIds: current.editorIds.includes(value) ? current.editorIds.filter((id) => id !== value) : [...current.editorIds, value] }));
  return <div className="mx-auto max-w-2xl space-y-6"><Link href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />返回工作台</Link><div><p className="text-sm font-medium text-primary">编辑工作台</p><h1 className="mt-2 text-3xl font-bold tracking-tight">创建新期刊</h1><p className="mt-2 text-sm text-muted-foreground">创建后即可开放投稿，发布前可以持续收集和审核稿件。</p></div><Card><CardHeader><CardTitle>期刊信息</CardTitle><CardDescription>请确认期数、人员和截止日期后再创建。</CardDescription></CardHeader><CardContent><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-medium">期数 *<Input className="mt-2" min="1" required type="number" value={form.id} onChange={(event) => update("id", event.target.value)} /></label><label className="block text-sm font-medium"><span className="flex items-center gap-2">截止日期 *<CalendarDays className="h-4 w-4 text-muted-foreground" /></span><Input className="mt-2" required type="datetime-local" value={form.deadline} onChange={(event) => update("deadline", event.target.value)} /></label></div>{[["subject2", "第二版主题"], ["subject3", "第三版主题"], ["subject4", "第四版主题"]].map(([field, label]) => <label className="block text-sm font-medium" key={field}>{label} *<Input className="mt-2" required value={form[field as keyof typeof form] as string} onChange={(event) => update(field as keyof typeof form, event.target.value)} /></label>)}<div className="grid gap-4 sm:grid-cols-2"><UserSelect label="Leader" value={form.leaderId} users={users} onChange={(value) => update("leaderId", value)} /><UserSelect label="Responsible editor" value={form.responsibleEditorId} users={users} onChange={(value) => update("responsibleEditorId", value)} /></div><label className="block text-sm font-medium">Editors（可多选）<div className="mt-2 grid max-h-44 gap-2 overflow-y-auto rounded-md border border-input bg-background p-3 sm:grid-cols-2">{users.map((user) => <label className="flex cursor-pointer items-center gap-2 rounded px-2 py-2 text-sm hover:bg-muted" key={user.id}><input type="checkbox" checked={form.editorIds.includes(String(user.id))} onChange={() => toggleEditor(String(user.id))} />{user.username}<span className="ml-auto text-xs text-muted-foreground">{user.grade}-{user.classnum}</span></label>)}{users.length === 0 && <span className="text-sm text-muted-foreground">暂无可选用户</span>}</div></label>{error && <p className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2 border-t pt-5"><Link href="/"><Button type="button" variant="outline">取消</Button></Link><Button disabled={submitting || users.length === 0} type="submit">{submitting ? <Spinner className="mr-2" /> : <FilePlus2 className="mr-2 h-4 w-4" />}创建期刊</Button></div></form></CardContent></Card></div>;
}

function UserSelect({ label, value, users, onChange }: { label: string; value: string; users: UserChoice[]; onChange: (value: string) => void }) { return <label className="block text-sm font-medium">{label}<select className="mt-2 flex h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" value={value} onChange={(event) => onChange(event.target.value)}><option value="">未指定</option>{users.map((user) => <option key={user.id} value={user.id}>{user.username}（{user.grade}-{user.classnum}）</option>)}</select></label>; }
