# Generated by Django 5.2.17 on 2026-09-15 03:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('scope', models.CharField(max_length=100)),
                ('executor', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(max_length=16)),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('report', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField()),
                ('subject2', models.CharField(blank=True, max_length=255)),
                ('subject3', models.CharField(blank=True, max_length=255)),
                ('subject4', models.CharField(blank=True, max_length=255)),
                ('leader', models.CharField(blank=True, max_length=150)),
                ('editors', models.JSONField(blank=True, default=list)),
                ('responsible_editor', models.CharField(blank=True, max_length=150)),
                ('published', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, upload_to='issues/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issue_number'],
                'permissions': [('create_issue', 'Can create issues'), ('publish_issue', 'Can publish issues')],
            },
        ),
        migrations.CreateModel(
            name='LegacyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=150)),
                ('node', models.CharField(max_length=255)),
                ('source', models.CharField(default='orion.db', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('value_type', models.CharField(default='str', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('classnum', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('legacy_password_hash', models.CharField(blank=True, max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('access_management', 'Can access Current management')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, upload_to='entries/')),
                ('page', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('wordcount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('selector_name', models.CharField(blank=True, max_length=150)),
                ('reviewer_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '已审核'), ('selected', '已选录')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='current.issue')),
            ],
            options={
                'ordering': ['page', 'created_at'],
                'permissions': [('create_entry', 'Can create entries'), ('review_entry', 'Can review entries'), ('select_entry', 'Can select entries'), ('remove_entry', 'Can remove entries')],
            },
        ),
    ]
