# Generated by Django 5.2.17 on 2026-09-15 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False),
        ),
    ]
