# Generated by Django 5.2.17 on 2026-09-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_alter_entry_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacySession',
            fields=[
                ('session', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Legacy session archive',
                'verbose_name_plural': 'Legacy session archives',
            },
        ),
        migrations.CreateModel(
            name='LegacySudo',
            fields=[
                ('token', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('activity_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Legacy sudo archive',
                'verbose_name_plural': 'Legacy sudo archives',
            },
        ),
    ]
