# Generated by Django 5.2.17 on 2026-09-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0003_legacysession_legacysudo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacyPermission',
        ),
        migrations.DeleteModel(
            name='LegacySession',
        ),
        migrations.DeleteModel(
            name='LegacySudo',
        ),
    ]
