# Generated by Django 5.2.17 on 2026-09-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0004_delete_legacypermission_delete_legacysession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
