# Generated by Django 5.2.17 on 2026-09-15 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_issue_users(apps, schema_editor):
    Issue = apps.get_model("current", "Issue")
    User = apps.get_model("current", "User")
    for issue in Issue.objects.all():
        if issue.leader:
            leader = User.objects.filter(username=issue.leader.strip()).first()
            if leader:
                issue.leader_user_id = leader.pk
        if issue.responsible_editor:
            responsible_editor = User.objects.filter(username=issue.responsible_editor.strip()).first()
            if responsible_editor:
                issue.responsible_editor_user_id = responsible_editor.pk
        issue.save(update_fields=["leader_user_id", "responsible_editor_user_id"])

        editor_names = issue.editors if isinstance(issue.editors, list) else [name.strip() for name in (issue.editors or "").split(",") if name.strip()]
        editor_ids = User.objects.filter(username__in=editor_names).values_list("pk", flat=True)
        issue.editors_users.set(editor_ids)


def reverse_copy_issue_users(apps, schema_editor):
    # The old string fields are intentionally not restored during rollback.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0005_remove_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='responsible_editor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='editors_users',
            field=models.ManyToManyField(blank=True, related_name='edited_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_issue_users, reverse_copy_issue_users),
        migrations.RemoveField(
            model_name='issue',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='responsible_editor',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='leader_user',
            new_name='leader',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='editors_users',
            new_name='editors',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='responsible_editor_user',
            new_name='responsible_editor',
        ),
    ]
