# Generated by Django 5.2.17 on 2026-09-15 08:19

import current.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_review_history(apps, schema_editor):
    Entry = apps.get_model("current", "Entry")
    EntryFileVersion = apps.get_model("current", "EntryFileVersion")
    User = apps.get_model("current", "User")

    for entry in Entry.objects.all():
        submitter = User.objects.filter(username=entry.selector_name.strip()).first() if entry.selector_name.strip() else None
        reviewer = User.objects.filter(username=entry.reviewer_name.strip()).first() if entry.reviewer_name.strip() else None
        entry.submitter = submitter
        if entry.status in ("reviewed", "selected"):
            entry.review_completed_by = reviewer
            entry.review_completed_at = entry.updated_at
        if entry.status == "selected":
            entry.merged_at = entry.updated_at
        entry.save(update_fields=("submitter", "review_completed_by", "review_completed_at", "merged_at"))

        if entry.file:
            version = EntryFileVersion.objects.create(
                entry=entry,
                version=1,
                filename=entry.filename or entry.file.name.rsplit("/", 1)[-1],
                file=entry.file.name,
                uploader=reviewer or submitter,
                uploader_name=entry.reviewer_name or entry.selector_name,
                source="legacy",
                note="由现有稿件文件建立的初始版本",
            )
            EntryFileVersion.objects.filter(pk=version.pk).update(created_at=entry.created_at)


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0006_remove_issue_editors_alter_issue_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='review_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_entry_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=150)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_comments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='current.entry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EntryFileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=current.models.entry_version_upload_to)),
                ('uploader_name', models.CharField(blank=True, max_length=150)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(choices=[('submission', '投稿'), ('review', '审核修订'), ('legacy', '旧系统导入')], default='review', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='current.entry')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_entry_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version'],
                'constraints': [models.UniqueConstraint(fields=('entry', 'version'), name='unique_entry_file_version')],
            },
        ),
        migrations.RunPython(seed_review_history, migrations.RunPython.noop),
    ]
