# Generated by Django 5.2.17 on 2026-09-15 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_state_events(apps, schema_editor):
    Entry = apps.get_model("current", "Entry")
    EntryStateEvent = apps.get_model("current", "EntryStateEvent")

    for entry in Entry.objects.filter(status__in=("reviewed", "selected")):
        reviewed_at = entry.review_completed_at or entry.updated_at
        review_event = EntryStateEvent.objects.create(
            entry=entry,
            action="review_completed",
            actor=entry.review_completed_by,
            actor_name=entry.reviewer_name,
            from_status="created",
            to_status="reviewed",
            note="由现有稿件状态建立的审核记录",
        )
        EntryStateEvent.objects.filter(pk=review_event.pk).update(created_at=reviewed_at)

        if entry.status == "selected":
            entry.closed_from_status = "reviewed"
            entry.save(update_fields=("closed_from_status",))
            merged_at = entry.merged_at or entry.updated_at
            merge_event = EntryStateEvent.objects.create(
                entry=entry,
                action="closed_merged",
                actor=entry.merged_by,
                actor_name=entry.merged_by.username if entry.merged_by else "",
                from_status="reviewed",
                to_status="selected",
                note="由现有已选录状态建立的合并记录",
            )
            EntryStateEvent.objects.filter(pk=merge_event.pk).update(created_at=merged_at)


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0007_entry_merged_at_entry_merged_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='closed_from_status',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并'), ('invalid', '已关闭：无效')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='EntryStateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('review_completed', '完成审核'), ('closed_invalid', '关闭为无效'), ('closed_merged', '关闭为已合并'), ('reopened', '重新打开')], max_length=24)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_state_events', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='current.entry')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(seed_state_events, migrations.RunPython.noop),
    ]
