# Generated by Django 5.2.17 on 2026-09-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0008_entry_closed_from_status_alter_entry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrystateevent',
            name='action',
            field=models.CharField(choices=[('review_completed', '完成审核'), ('review_returned', '退回重新审核'), ('closed_invalid', '关闭为无效'), ('closed_merged', '关闭为已合并'), ('reopened', '重新打开')], max_length=24),
        ),
    ]
