# Generated by Django 5.2.17 on 2026-09-15 12:17

from django.db import migrations, models


def migrate_legacy_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("current", "User")
    permissions = {
        permission.codename: permission
        for permission in Permission.objects.filter(content_type__app_label="current")
    }
    create_entry = permissions.get("create_entry")
    if create_entry:
        for user in User.objects.all():
            user.user_permissions.add(create_entry)

    group_permissions = {
        "Current Editors": ("review_entry",),
        "Current Chief Editors": ("select_entry",),
    }
    for group_name, codenames in group_permissions.items():
        group = Group.objects.filter(name=group_name).first()
        if not group:
            continue
        direct_permissions = [permissions[codename] for codename in codenames if codename in permissions]
        for user in group.user_set.all():
            user.user_permissions.add(*direct_permissions)

    administrators = Group.objects.filter(name="Current Administrators").first()
    if administrators:
        for user in administrators.user_set.all():
            user.user_permissions.add(*permissions.values())
            user.is_staff = True
            user.save(update_fields=("is_staff",))

    Group.objects.filter(name__in=("Current Users", "Current Editors", "Current Chief Editors", "Current Administrators")).delete()
    Permission.objects.filter(
        content_type__app_label="current",
        content_type__model__in=("legacypermission", "legacysession", "legacysudo"),
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0009_alter_entrystateevent_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': '审计日志', 'verbose_name_plural': '审计日志'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['page', 'created_at'], 'permissions': [('create_entry', '创建投稿'), ('review_entry', '审核稿件'), ('select_entry', '终审稿件'), ('remove_entry', '删除稿件')], 'verbose_name': '稿件', 'verbose_name_plural': '稿件'},
        ),
        migrations.AlterModelOptions(
            name='entrycomment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '稿件留言', 'verbose_name_plural': '稿件留言'},
        ),
        migrations.AlterModelOptions(
            name='entryfileversion',
            options={'ordering': ['version'], 'verbose_name': '稿件文件版本', 'verbose_name_plural': '稿件文件版本'},
        ),
        migrations.AlterModelOptions(
            name='entrystateevent',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '稿件状态记录', 'verbose_name_plural': '稿件状态记录'},
        ),
        migrations.AlterModelOptions(
            name='importrun',
            options={'verbose_name': '数据导入记录', 'verbose_name_plural': '数据导入记录'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-issue_number'], 'permissions': [('create_issue', '创建期刊'), ('publish_issue', '发布期刊')], 'verbose_name': '期刊', 'verbose_name_plural': '期刊'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': '站点配置', 'verbose_name_plural': '站点配置'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_management', '访问 Current 管理功能')], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='classnum',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='年级'),
        ),
        migrations.RunPython(migrate_legacy_groups, migrations.RunPython.noop),
    ]
