# Generated by Django 5.2.17 on 2026-09-16 10:11

import current.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0010_modernize_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='executor',
            field=models.CharField(blank=True, max_length=150, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='message',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='scope',
            field=models.CharField(max_length=100, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='closed_from_status',
            field=models.CharField(blank=True, choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并'), ('invalid', '已关闭：无效')], max_length=16, verbose_name='关闭前状态'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.TextField(blank=True, verbose_name='投稿说明'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.FileField(blank=True, upload_to='entries/', verbose_name='当前文件'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='当前文件名'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='current.issue', verbose_name='所属期刊'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='merged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='合并时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='merged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_entries', to=settings.AUTH_USER_MODEL, verbose_name='合并者'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='page',
            field=models.PositiveSmallIntegerField(verbose_name='版面'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核完成时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='review_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_entry_reviews', to=settings.AUTH_USER_MODEL, verbose_name='完成审核者'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='审核人记录'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='selector_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='旧系统选稿人记录'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并'), ('invalid', '已关闭：无效')], default='pending', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_entries', to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=128, primary_key=True, serialize=False, verbose_name='稿件 ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='wordcount',
            field=models.PositiveIntegerField(default=0, verbose_name='字数'),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_comments', to=settings.AUTH_USER_MODEL, verbose_name='留言者'),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='author_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='留言者记录'),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='body',
            field=models.TextField(max_length=4000, verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='留言时间'),
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='current.entry', verbose_name='稿件'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='current.entry', verbose_name='稿件'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='file',
            field=models.FileField(upload_to=current.models.entry_version_upload_to, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='filename',
            field=models.CharField(max_length=255, verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='版本说明'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='source',
            field=models.CharField(choices=[('submission', '投稿'), ('review', '审核修订'), ('legacy', '旧系统导入')], default='review', max_length=16, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_entry_versions', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='uploader_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='上传者记录'),
        ),
        migrations.AlterField(
            model_name='entryfileversion',
            name='version',
            field=models.PositiveIntegerField(verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='action',
            field=models.CharField(choices=[('review_completed', '完成审核'), ('review_returned', '退回重新审核'), ('closed_invalid', '关闭为无效'), ('closed_merged', '关闭为已合并'), ('reopened', '重新打开')], max_length=24, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_state_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='actor_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='操作人记录'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_events', to='current.entry', verbose_name='稿件'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并'), ('invalid', '已关闭：无效')], max_length=16, verbose_name='原状态'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='entrystateevent',
            name='to_status',
            field=models.CharField(choices=[('pending', '待投稿'), ('created', '已投稿'), ('reviewed', '审核完成'), ('selected', '已合并'), ('invalid', '已关闭：无效')], max_length=16, verbose_name='新状态'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='mode',
            field=models.CharField(max_length=16, verbose_name='导入模式'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='report',
            field=models.JSONField(default=dict, verbose_name='导入报告'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='source_fingerprint',
            field=models.CharField(max_length=64, verbose_name='数据源指纹'),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateTimeField(verbose_name='截稿时间'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='edited_issues', to=settings.AUTH_USER_MODEL, verbose_name='审核编辑'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='期号'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_issues', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='pdf',
            field=models.FileField(blank=True, upload_to='issues/', verbose_name='报刊 PDF'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='published',
            field=models.BooleanField(default=False, verbose_name='已出版'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='responsible_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_issues', to=settings.AUTH_USER_MODEL, verbose_name='主编'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject2',
            field=models.CharField(blank=True, max_length=255, verbose_name='第二版主题'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject3',
            field=models.CharField(blank=True, max_length=255, verbose_name='第三版主题'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='subject4',
            field=models.CharField(blank=True, max_length=255, verbose_name='第四版主题'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='key',
            field=models.CharField(max_length=100, unique=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='value',
            field=models.TextField(blank=True, verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='value_type',
            field=models.CharField(default='str', max_length=16, verbose_name='值类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legacy_password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='旧系统密码摘要'),
        ),
    ]
