export type User = { id: number; username: string; grade: number; classnum: number; is_active: boolean; is_staff: boolean };
export type UserChoice = { id: number; username: string; grade: number; classnum: number; is_active: boolean; is_staff: boolean };
export type Issue = { id: number; deadline: string; subject: string[]; leader: UserChoice | null; editors: UserChoice[]; responsible_editor: UserChoice | null; published: boolean; pdf_available: boolean; can_manage_pdf: boolean };
export type EntryStatus = "pending" | "created" | "reviewed" | "selected" | "invalid";
export type Entry = { uuid: string; issue_id: number; filename: string; page: number; title: string; origin: string; wordcount: number; description: string; submitter: UserChoice | null; selector_name: string; reviewer_name: string; status: EntryStatus; closed_from_status: string; review_completed_by: UserChoice | null; review_completed_at: string | null; merged_by: UserChoice | null; merged_at: string | null; version_count: number; comment_count: number; created_at: string; updated_at: string };
export type EntryFileVersion = { id: number; version: number; filename: string; uploader: UserChoice | null; uploader_name: string; note: string; source: "submission" | "review" | "legacy"; created_at: string; download_url: string };
export type EntryComment = { id: number; author: UserChoice | null; author_name: string; body: string; created_at: string };
export type EntryStateEvent = { id: number; action: "review_completed" | "review_returned" | "closed_invalid" | "closed_merged" | "reopened"; actor: UserChoice | null; actor_name: string; from_status: string; to_status: string; note: string; created_at: string };
export type EntryCapabilities = { can_comment: boolean; can_upload_version: boolean; can_complete_review: boolean; can_return_to_review: boolean; can_merge: boolean; can_close: boolean; can_reopen: boolean; can_delete: boolean };
export type EntryReview = Entry & { versions: EntryFileVersion[]; comments: EntryComment[]; state_events: EntryStateEvent[]; capabilities: EntryCapabilities };
export type AnnouncementManager = { draft: string; published: string; published_at: string; published_by: string };
export type Statistics = {
  generated_at: string;
  ranking_period: "latest" | "recent3" | "all";
  summary: { issues: number; published_issues: number; entries: number; words: number; versions: number; comments: number };
  status_counts: Record<EntryStatus, number>;
  workflow: { average_review_hours: number | null; average_decision_hours: number | null; returned_reviews: number; reopened_entries: number };
  issues: Array<{ id: number; published: boolean; total: number; pending: number; waiting: number; reviewed: number; merged: number; invalid: number; words: number }>;
  pages: Array<{ page: number; total: number; merged: number; words: number }>;
  contributors: Array<{ username: string; entries: number; words: number; merged: number }>;
  collaborators: Array<{ username: string; reviews: number; merges: number; comments: number; versions: number }>;
  personal: { submitted: number; merged: number; reviewing: number; awaiting_decision: number };
};
